### ISSUE TITLE
Questions...

### ISSUE THREAD

**Issue by behrad** [strongloop/loopback-example-embedded-relations#1]
I couldn't find my answer in docs, so asked here:

1) What does `model.embedsOne.build` method do and how is it different with `.create`

2) What does the REST api `refresh` boolean query parameter mean !?

**Comment by arealmaas** [comment]
1) `build` creates and returns a new instance of the model, `create` creates a new model and persists it in the DB. http://docs.strongloop.com/display/public/LB/HasMany+relations

2) Should be in the docs somewhere i guess. http://docs.strongloop.com/display/public/LB/LoopBack

**Comment by behrad** [comment]
thank you @AlmaasAre I have a problem relating a mongo model to a redis model via belongsTo :(
Can you point me to somewhere so I can debug this issue !?

**Comment by arealmaas** [comment]
@behrad hard to say without knowing the exact issue, but i guess you can look around at https://github.com/strongloop/loopback-connector-mongodb/issues or something. 

If you're using loopback-connector-redis, it states that it's very experimental, so maybe you should report your issue. http://docs.strongloop.com/display/public/LB/Redis+connector

**Comment by behrad** [comment]
thanks @AlmaasAre , closing this.
